### ISSUE TITLE
Open in local Devcontainer fails

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/opengeohub2023#14]
As shown below, Reopen in Devcontainer fails locally. 

![image](https://github.com/Robinlovelace/opengeohub2023/assets/1825120/a66899fc-2e75-4882-bed8-cbb680b5157e)

No idea why, as it works on Codespaces: https://codespaces.new/Robinlovelace/opengeohub2023

**Comment by Robinlovelace** [comment]
See log with message below:

```
[40 ms] Dev Containers 0.304.0 in VS Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794).
[40 ms] Start: Resolving Remote
[86 ms] Setting up container for folder or workspace: /home/robin/github/robinlovelace/opengeohub2023
[88 ms] Start: Check Docker is running
[88 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[111 ms] Server API version: 1.43
[113 ms] Start: Run: docker volume ls -q
[132 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/robin/github/robinlovelace/opengeohub2023 --filter label=vsch.quality=stable
[151 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --filter label=devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json
[168 ms] Start: Run: docker inspect --type container 20a7e66a6d78
[186 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023
[203 ms] Start: Run: docker inspect --type container 20a7e66a6d78
[221 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/robin/github/robinlovelace/opengeohub2023 --id-label devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --id-label devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json --log-level debug --log-format json --config /home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json --mount-workspace-git-root true
[383 ms] @devcontainers/cli 0.50.0. Node.js v16.17.1. linux 6.2.0-26-generic x64.
[383 ms] Start: Run: git rev-parse --show-cdup
[388 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --filter label=devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json
[403 ms] Start: Run: docker inspect --type container 20a7e66a6d78
[652 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/robin/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-87da8aa8-5095-4ac2-96bc-5284bd68758f1693295762481 --workspace-folder /home/robin/github/robinlovelace/opengeohub2023 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --id-label devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json --log-level debug --log-format json --config /home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-93278322-f28b-45a6-948a-0ecd71a848fe.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[806 ms] @devcontainers/cli 0.50.0. Node.js v16.17.1. linux 6.2.0-26-generic x64.
[806 ms] Start: Run: docker buildx version
[856 ms] github.com/docker/buildx v0.11.2 9872040
[856 ms] 
[856 ms] Start: Resolving Remote
[858 ms] Start: Run: git rev-parse --show-cdup
[1037 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --filter label=devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json
[1063 ms] Start: Run: docker inspect --type container 20a7e66a6d78
[1084 ms] Start: Starting container
[1084 ms] Start: Run: docker start 20a7e66a6d781771054e1de507c48420c153922e9b0e95269065879b3f96b3e7
[1438 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --filter label=devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json
[1455 ms] Start: Run: docker inspect --type container 20a7e66a6d78
[1707 ms] Start: Inspecting container
[1707 ms] Start: Run: docker inspect --type container 20a7e66a6d781771054e1de507c48420c153922e9b0e95269065879b3f96b3e7
[1728 ms] Start: Run in container: /bin/sh
[1732 ms] Start: Run in container: uname -m
[1746 ms] Shell server terminated (code: 1, signal: null)
[1746 ms] Error response from daemon: Container 20a7e66a6d781771054e1de507c48420c153922e9b0e95269065879b3f96b3e7 is not running
[1746 ms] Start: Run in container: getent passwd vscode
[1746 ms] Stdin closed!
[1746 ms] Error: An error occurred setting up the container.
[1746 ms]     at oAA (/home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1066)
[1746 ms]     at mK (/home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1002)
[1747 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[1747 ms]     at async mAA (/home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[1747 ms]     at async LC (/home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[1747 ms]     at async jeA (/home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:12219)
[1747 ms]     at async _eA (/home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:11960)
[1751 ms] Exit code 1
[1754 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/robin/.vscode/extensions/ms-vscode-remote.remote-containers-0.304.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/robin/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-87da8aa8-5095-4ac2-96bc-5284bd68758f1693295762481 --workspace-folder /home/robin/github/robinlovelace/opengeohub2023 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/robin/github/robinlovelace/opengeohub2023 --id-label devcontainer.config_file=/home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json --log-level debug --log-format json --config /home/robin/github/robinlovelace/opengeohub2023/.devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-93278322-f28b-45a6-948a-0ecd71a848fe.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1754 ms] Exit code 1
```
